# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://peregrinator.site"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

timeout = 60

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
blog = "/:section/:year/:month/:filename"
misc = "/:section/:year/:month/:filename"
emacs = "/:section/:slug"
fiction = "/:section/:year/:month/:filename"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.highlight]
tabWidth = 2
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false

[taxonomies]
series = "series"

[params]
ogImage = "https://peregrinator.site/img/avatar.png"
ogImagealt = "A silhoutte of a Shaheen falcon"
fediCreator1 = "@peregrinator@fosstodon.org"
fediCreator2 = "@peregrinator@mastodon.social"
fediCreator3 = "@peregrinator@lemmy.ml"

[privacy]
  [privacy.x]
    disable = false
    enableDNT = true
    simple = false
