baseURL = "https://peregrinator.site"
title = "Peregrinator's blog"

dateFormat = "02.01.2006"

mainSections = ["blog"]

defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

timeout = 60

# use class names instead of directly inserting color codes
pygmentsUseClasses = true
# enable GitHub style code snippets
pygmentsCodeFences = true


# Site parameters
[params]
  logo="/images/logo.jpg"
  ogImage = "/images/og_image.jpg"
  twtImage = "/images/twitter_image.jpg"
  ogImagealt = "a juvenile Shaheen with a Pond heron Kill. Photo by GK; see https://peregrinator.site/about/"
  # Site Author
  author = "Brihadeesh S"
  email = "contact@peregrinator.site"
  # Author biography
  # bio = "Ecologist who's also into loud and dark music"
  # Site Description, used in HTML meat
  # description = "thoughts and musings about Ecology, Open Source software, music and mental health"
  # Website copyright, default: '© Copyright 2021 ❤️ {params.author}'
  copyright = "The content for this site is [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) or [GPL 3.0 or later](https://www.gnu.org/licenses/gpl-3.0.html), the [source code](https://git.sr.ht/~peregrinator/peregrinator.site) for this site is [MIT](https://git.sr.ht/~peregrinator/peregrinator.site/tree/main/item/LICENSE). Read the notice about [privacy](/privacy)."
  # dark = "off"
  highlight = true

[pagination]
  pagerSize = 100

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
blog = "/:section/:year/:month/:filename"
fiction = "/:section/:year/:month/:filename"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.highlight]
tabWidth = 2
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false

[taxonomies]
series = "series"

[privacy]
  [privacy.x]
    disable = false
    enableDNT = true
    simple = false
