baseURL = "https://peregrinator.site"
title = "peregrinator's blog"

dateFormat = "02.01.2006"

mainSections = ["blog"]

defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

timeout = 60

# use class names instead of directly inserting color codes
pygmentsUseClasses = true
# enable GitHub style code snippets
pygmentsCodeFences = true


# Site parameters
[params]
  ogImage = "images/avatar.png"
  ogImagealt = "A silhoutte of a Shaheen falcon"
  # Site Author
  author = "Brihadeesh S"
  email = "contact@peregrinator.site"
  # Author biography
  # bio = "Ecologist who's also into loud and dark music"
  # Site Description, used in HTML meat
  # description = "thoughts and musings about Ecology, Open Source software, music and mental health"
  # Website copyright, default: '© Copyright 2021 ❤️ {params.author}'
  copyright = "The content for this site is [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/), the [source code](https://github.com/brihadeesh/peregrinator.site) for this site is [MIT](https://github.com/brihadeesh/peregrinator.site/blob/main/LICENSE)"
  # dark = "off"
  highlight = true

[pagination]
  pagerSize = 100

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
blog = "/:section/:year/:month/:filename"
misc = "/:section/:year/:month/:filename"
fiction = "/:section/:year/:month/:filename"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.highlight]
tabWidth = 2
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false

[taxonomies]
series = "series"

[privacy]
  [privacy.x]
    disable = false
    enableDNT = true
    simple = false
