image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- hugo
- go
sources:
  - https://git.sr.ht/~sircmpwn/openring
environment:
  site: peregrinator.site
tasks:
- openring: |
    cd openring
    go build -o openring
    sudo cp openring /usr/local/bin/
- build: |
    cd $site
    /usr/local/bin/openring \
    -s https://drewdevault.com/blog/index.xml \
    -s https://sourcehut.org/blog/index.xml \
    -s https://emersion.fr/blog/atom.xml \
    -s https://popagandhi.com/index.xml \
    < webring-in.template \
    > layouts/partials/webring-out.html
    hugo
- package: |
    cd $site
    tar -C public -cvz . > site.tar.gz
- upload: |
    cd $site
    hut pages publish -d $site site.tar.gz
