baseURL = "https://brihadeesh.github.io/"
title = "peregrinator's blog"
pygmentsUseClasses = true
disablePathToLower = true
rssLimit = 10
uglyurls = true
relativeURLs = true
languageCode = 'en-us'
enableInlineShortcodes = true

copyright = "2012-2023 Brihadeesh S All rights reserved"

[Author]
name = "Brihadeesh"
email = "~pereginator/public_inbox@lists.sr.ht"


[permalinks]
blog = "/:section/:year/:month/:filename"
misc = "/:section/:year/:month/:filename"
emacs = "/:section/:slug"
fiction = "/:section/:year/:month/:filename"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
tabWidth = 2
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false

[markup.tableOfContents]
ordered = true
endLevel = 6

[outputs]
section = ["HTML", "RSS"]
