baseURL = "https://peregrinator.site/"
title = "peregrinator's blog"
pygmentsUseClasses = true
disablePathToLower = true
rssLimit = 10
uglyurls = true
relativeURLs = true
languageCode = 'en-us'
enableInlineShortcodes = true

# temp
# ignoreErrors = ["error-remote-getjson"]

copyright = "2012-2023 Brihadeesh S All rights reserved"

[Author]
name = "Brihadeesh S"
email = "brihadeesh.s@proton.me"


[permalinks]
blog = "/:section/:year/:month/:filename"
misc = "/:section/:year/:month/:filename"
emacs = "/:section/:slug"
fiction = "/:section/:year/:month/:filename"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
tabWidth = 2
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false

[markup.tableOfContents]
ordered = true
endLevel = 6

[outputs]
section = ["HTML", "RSS"]

[params]
ogImage = "https://peregrinator.site/avatar.jpg
ogImagealt = " "
fediCreator = "@peregrinator@mastodon.social"
summaryLength = "10"