#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: /
#+HUGO_CUSTOM_FRONT_MATTER: :toc false

#+title: peregrinator's blog

Skip ahead to the [[/#posts-archive][posts]] directly

I've been writing since 2016 when I first wanted to talk about ecology
and natural history in a less technical fashion so it would be more
approachable for people without training in the field. That blog was
hosted on a free Wordpress site. Later events, however, got me
interested in computers and open source software so I let that wave
take me to writing about my experiences with it and he rest is what
you see on this website. I moved from Wordpress to what I'm using
currently in 2022 and [[/blog/2022/12/hugo-org-and-starting-over-at-a-new-blog/][wrote about the move]] too! I've been listening to
all kinds of music since fairly early on and I've more recently
started writing about that too.

I've not organised posts with tags, or in any way really, but some of
them are parts of series, as you might discover as you read. I don't
intent to have comments displayed on posts either but you can [[mailto:~peregrinator/public_inbox@lists.sr.ht][write]] to
my [[https://lists.sr.ht/~peregrinator/public_inbox][public inbox]] or use the link at the bottom of every article to
reference specific posts. I do intend to bring the comments from the
old Wordpress blog to somewhere everyone can see them but I've not
made up my mind on how to do that.

* Emacs

I am a little unclear on how to organise articles I've written for the
blog that have to do with how I use Emacs as yet — i.e whether to have
them on the [[https://emacs.peregrinator.site][Emacs]] section of this website or here, on the blog itself
— so they are currently restricted to a series of posts on [[/series/blogging-with-emacs][Blogging
with Emacs]] here.

I've also included a single piece of (fan)fiction I wrote as part of
an English assignment, inspired by Herman Melville's /Moby Dick/ in the
[[/fiction/2012/05/ahab/][fiction]] section of the website.

* Other lists

1. [[/blogroll][Blogroll]] of all the blogs I read
2. [[/books][Books I've read]] or those I'm reading
3. [[/links][Interesting links]] — various blog posts and other useful links I've found
   over time
4. [[https://emacs.peregrinator.site/resources][Emacs resources]] over on the Emacs section of the website
