#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: /
#+HUGO_CUSTOM_FRONT_MATTER: :toc false :layout "about" :showDate false :showAuthor false :showBreadcrumbs true :showReadingTime false

#+title: about me

I'm a 29 year old, neurodivergent, cat supremacist that sometimes
cosplays as an ecologist. I'm big on F(L)OSS and currently run a [[https://voidlinux.org][Void
Linux]] installation with a manually compiled version of Emacs 29. I
also play the guitar, listen to typically a lot of metal and try to
make my own music occasionally. I currently use [[https://ardour.org][Ardour 7.0]] for audio
production, which I'm very new to, and hope to get started with the
[[https://sonic-pi.net][Sonic Pi]] as both a standalone instrument as well as a synth for
instruments I don't play myself.

This is a /static/ website and is intended to (eventually) be the home
for my blog, Emacs configuration and work updates. I hope to
eventually move to or host it there. This website uses a stylised
version of the theme from [[https://drewdevault.com][Drew Devault]]'s blog within the same [[https://gohugo.io][Hugo]]
framework. Everything you see here was written in [[https:orgmode.org][Org-mode]] on Emacs,
exported to markdown via [[https://github.com/kaushalmodi/ox-hugo][ox-hugo]] for better compatibility - the
default [[https://github.com/niklasfasching/go-org][go-org]] parser doesn't appear to handle Org syntax
adequately. Read more about my blogging flow on my [[file:/blog/2022/12/hugo-org-and-starting-over-at-a-new-blog.html][post]] about it.

The source for this website is on my [[https://git.sr.ht/~peregrinator/peregrinator.site][Sourcehut]].

* Publications

** 1. A contribution on morphology and distribution of the Rock Toad Duttaphrynus hololius (Günther, 1876) with first report on deformity, calling and breeding behaviours (Amphibia: Anura: Bufonidae)

[[https://ajcb.in/archive_july_20.php][July 2020: Asian Journal of Conservation Biology 9(1):71-78]]

#+hugo: {{< embed-pdf url="/pdfs/jul2020_AJCB.pdf" >}}

** 2. Focal Plant and Neighbourhood Fruit Crop Size Effects on Fruit Removal by Frugivores in a Semi-Arid Landscape Invaded by Lantana camara L.

[[https://www.jstor.org/stable/e27137849][February 2019: Current Science 116(3):405-411]]

#+hugo: {{< embed-pdf url="/pdfs/feb2019_CurSci.pdf" >}}

** 3. Discourage voice playbacks in the breeding season

[[https://indianbirds.in/vol-10-no-5/][November 2015: Indian BIRDS 10(5):140]]

#+hugo: {{< embed-pdf url="/pdfs/nov2015_IndianBirds.pdf" >}}

** 4. Nesting of the Spot-billed Duck Anas poecilorhyncha in Chennai city

[[https://indianbirds.in/vol-10-no-2/][June 2015: Indian BIRDS 10(2):55-56]]

#+hugo: {{< embed-pdf url="/pdfs/jun2015_IndianBirds.pdf" >}}
