#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: /
#+HUGO_CUSTOM_FRONT_MATTER: :showTableOfContents true :layout "about" :showDate false :showAuthor false :showBreadcrumbs true :showReadingTime false

#+title: Blogroll

I've only just started learning about things like the blogroll after
nearly 10 years of having a blog and I love reading so here's a bunch
of really cool people whose blogs you should also read.

1. [[https://drewdevault.com/][Drew Devault's blog]]: Drew founded Sourcehut, the Sway window
   manager, a lot more software and now maintains all of them. He
   writes about a variety of topics I find that his takes on political
   issues really resonate with mine. He truly embraces the open source
   philosophy in all of the ways I wish I could.
2. [[https://popagandhi.com/][Propagandhi]]: Adrianna Tan is someone I met and got to know on
   Mastodon and she writes a lot about food and what it's like to be
   neurodivergent.
3. [[https://amandaswritingblog9.wordpress.com/][Amanda's Writing Corner]]: Amanda is a musician and plays black/death
   metal. She writes fiction and set up this blog to put it out
   there. We've been friends for a while from Twitter (now Bluesky).
4. [[https://ambikamath.com/][Ambika Kamath]]: Ambika is an ecologist and has worked on lizards for
   her PhD. She writes about ecology and has currently co-authored a
   book called Feminism in the Wild.
5. [[https://noobheavy.com/][Noob Heavy]]: Kep, Westin, Ellis and Kirk run this wonderful blog on
   new and upcoming releases in the metal world. If you're also into
   metal, this is a must follow.
6. [[https://www.sleepingvillagereviews.com/][Sleeping Village Reviews]]: I've been friends with... erm... well I
   don't know his name, but well we've been friend for quite some time
   now from Twitter to now Bluesky. We discuss a lot of metal and he
   writes reviews for, well, all kinds of metal. You know the drill.
7. [[https://torontopubliclibra.com/][The Toronto Public Libra]]: Dana "Rusty" Rosamund Teagle is a friend
   from Bluesky and she has "spent her entire life being gay on a
   computer." Her blog is linked on her website.[fn:1:Dana uses a
   Substack and I feel like I shouldn't be providing the blogging
   service any traffic from my end since "its chief executive defended
   hosting and handling payments for “Nazis” on its platform, citing
   anti-censorship reasons." See [[https://www.theguardian.com/media/2024/jan/03/substack-user-revolt-anti-censorship-stance-neo-nazis][this article]] from The Guardian. Hence
   I've not provided a direct link to her Substack.]
8. [[https://medium.com/@seemamundoli][Seema Mundoli]]: Seema writes about her three quirky cats, CI Mykah,
   Fuzzu and Noori. They're a LOT of fun.
9. [[https://kevquirk.com/][Kev Quirk]]: Kev is a tech guy and he maintains the [[https:fosstodon.org][fosstodon.org]]
   instance on Mastodon. He writes about a variety of stuff but mostly
   just life, and watches.
10. [[https://falseknees.com/][False Knees]]: the hilarious bird comic!
11. [[https://shankarraman.in/][View from Elephant Hills]]: TR Shankar Raman has been an old family
    friend and he used to go birding with my father. He has been
    writing this blog for quite some time now and usually talks about
    ecological issues and bird-watching.
12. [[https://neilzone.co.uk/index.xml][Neil's blog]]: Neil Brown writes about tech and is very vocal about
    stuff that has to do with the internet. He's also very active on
    the Fediverse. His blog was one of the key contributors to my
    switching back to the Etch theme.
