#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: /
#+HUGO_CUSTOM_FRONT_MATTER: :showTableOfContents true :layout "about" :showDate false :showAuthor false :showBreadcrumbs true :showReadingTime false

#+title: Blogroll

I've only just started learning about things like the blogroll after
nearly 10 years of having a blog and I love reading so here's a bunch
of really cool people whose blogs you should also read.

1. [[https://drewdevault.com/][Drew Devault's blog]]: Drew founded Sourcehut, the Sway window
   manager, a lot more software and now maintains all of them. He
   writes about a variety of topics I find that his takes on political
   issues really resonate with mine. He truly embraces the open source
   philosophy in all of the ways I wish I could.
2. [[https://popagandhi.com/][Propagandhi]]: Adrianna Tan is someone I met and got to know on
   Mastodon and she writes a lot about food and what it's like to be
   neurodivergent.
3. [[https://amandaswritingblog9.wordpress.com/feed][Amanda's Writing Corner]]: Amanda is a musician and plays black/death
   metal. She writes fiction and set up this blog to put it out
   there. We've been friends for a while from Twitter (now Bluesky).
4. [[https://ambikamath.com/][Ambika Kamath]]: Ambika is an ecologist and has worked on lizards for
   her PhD. She writes about ecology and has currently co-authored a
   book called Feminism in the Wild.
5. [[https://noobheavy.com/][Noob Heavy]]: Kep, Westin, Ellis and Kirk run this wonderful blog on
   new and upcoming releases in the metal world. If you're also into
   metal, this is a must follow.
6. [[https://www.sleepingvillagereviews.com/][Sleeping Village Reviews]]: I've been friends with... erm... well I
   don't know his name, but well we've been friend for quite some time
   now from Twitter to now Bluesky. We discuss a lot of metal and he
   writes reviews for, well, all kinds of metal. You know the drill.
7. [[https://torontopubliclibra.substack.com/][The Toronto Public Libra]]: Dana "Rusty" Rosamund Teagle is a friend
   from Bluesky and she has "spent her entire life being gay on a
   computer." You can also find her on her [[https://torontopubliclibra.com/][work website]].
8. [[https://medium.com/@seemamundoli][Seema Mundoli]]: Seema writes about her three quirky cats, CI Mykah,
   Fuzzu and Noori. They're a LOT of fun.
9. [[https://kevquirk.com/][Kev Quirk]]: Kev is a tech guy and he maintains the [[https:fosstodon.org][fosstodon]]
   instance on Mastodon. He writes about a variety of stuff but mostly
   just life, and watches.
