#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: emacs
#+HUGO_URL: /emacs/colourless_themes.html
#+HUGO_PUBLISHDATE: 2023-03-19 Sun
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_CUSTOM_FRONT_MATTER: :autonumbering true
#+options: h:7 num:6
#+STARTUP: oddeven overview

#+title: Colourless themes for Emacs

#+attr_html: :class alert-info
#+begin_alert
This is a work in progress. You can browse the code on my [[https://git.sr.ht/~peregrinator/colourless-themes][sourcehut]].
#+end_alert


* Boring themes for the elitist

~colourless-themes~ is a collection of “primarily colourless
themes". This was forked from Tomas Letan's macro of the same
name.[fn:1: The macro is a rework of theirs — an opinionated take
perhaps? Find their source code at [[https://git.sr.ht/~lthms/colorless-themes.el][~lthms/colorless-themes.el]]]

** Installation

Install this how you would install a package from github - this varies
with the flavour of Emacs or the setup in use. If you use a
Frankenstein's monster like I use, do:

#+BEGIN_SRC emacs-lisp :tangle no
  (use-package colourless-themes
    :straight (:host sourcehut
     :repo "~peregrinator/colourless-themes-el")

    :config
    ;;optionally loading a theme
    (load-theme 'einkless t)
#+END_SRC

** Usage

Temporarily set it the ~M-x load-theme~ , or via ~M-x
customize-themes~. To make it persistent, see [[file:/emacs/colourless_themes.html#installation][Installation]]. Disable
any other themes to ensure a colourless experience.

* Featured themes

Themes offered besides those from upstream are

- ~mephistopheles~ an original dark theme with yellow and green
  foreground, again inspired by Stanislav Karkavin's vim theme
  mentioned above.
- ~beelzebub~ A dark, purplish colourscheme based on Stanislav
  Karkavin's vim theme: [[https://github.com/xdefrag/vim-beelzebub][vim-beelzebub]]
- ~nofrils~, Emacs ports /faithful/ to the [[https://github.com/robertmeta/nofrils][original nofrils
  themes]]. These have a few more colours than the others.

** Screenshots

WIP
